### ISSUE TITLE
Docker Image not working

### ISSUE THREAD

**Issue by samcro1967** [JustKato/FreePad#11]
The docker image is not working.  If I understand the Dockerfile, it is copying the contents from the dist folder in the repo to the app folder in the image and then running freepad from there.  No files are present in the repo dist folder.  I do not see the freepad binary in the repo either.  Perhaps your intent was to build the executable in that folder as part of the Dockerfile build process and then copy it to the image app folder?

<details>
  <summary>docker-compose up logs</summary>

```
Starting freepad ... error

ERROR: for freepad  Cannot start service freepad: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./freepad": stat ./freepad: no such file or directory: unknown

ERROR: for freepad  Cannot start service freepad: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./freepad": stat ./freepad: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```
</details>

**Comment by JustKato** [comment]
Hey sam, you need to first run the build script, this will fill in the `dist` folder and you will be able to build the docker image, sorry for this annoying extra step, I will be adding this into the docker build process.

**Comment by samcro1967** [comment]
I would suggesting moving the steps in build.sh to the Dockerfile and eliminating the manual build script.  You can even have the download of the source code as part of the Dockerfile if you want so it is one command for folks to run and build it.  Here is an example of one I created for a go app if it helps you.
<details>
<summary>Dockerfile example</summary>

```
FROM golang:1.17.5-alpine3.15 AS Builder
WORKDIR /app
RUN \
  echo "**** install packages ****" && \
  apk update && \
  apk add git && \
  git clone https://github.com/adnanh/webhook.git
WORKDIR /app/webhook
RUN go mod download -x
RUN go mod tidy
RUN GOOS=linux GOARCH=amd64 go build -o webhook

FROM alpine:3.15
COPY --from=builder /app/webhook /bin/
RUN \
  apk update && \
  apk add \
    curl \
	docker \
	docker-compose && \
  curl -L https://github.com/harness/drone-cli/releases/latest/download/drone_linux_amd64.tar.gz | tar zx && \
  install -t /usr/local/bin drone
ENV PATH="$PATH:/config:/app/webhook"
CMD webhook -debug -port 9358 -hooks /config/hooks.yml -hotreload

# ports and volumes
EXPOSE 9358
VOLUME /config
```
</details>

**Comment by JustKato** [comment]
Thank you so much for the example, really is helping out, I'll get to implementing it as soon as possible! Thanks so much! :)

**Comment by samcro1967** [comment]
Just tested and it works as expected.
